name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build SPA app
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm install
      # - run: npm test
      - run: npx ng build --prod

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXTRA_SJAJ }}
